apiVersion: v1
data:
  htpasswd: YWRtaW46JDJ5JDA1JFg0NkVtUmNXem1WMnpmWlM4SnVPWnUyNmI0Q1Izem44YUtzdXNTLnUxWGs4c09ZTGVPeGkuCmRldmVsb3BlcjokMnkkMDUkOFVPZEJPbWlXVFVuaGxaZzBocTRDZVE3di9kdFFsZWkwcEx1L01HVE5JeXJaaVJTLktEbHEK
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
type: Opaque
