---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: priorityclass-cluster-role
rules:
- apiGroups: [""]
  resources: ["priorityclass"]
  verbs: ["*"]
- apiGroups: ["scheduling.k8s.io"]
  resources: ["priorityclasses"]
  verbs: ["create","patch"]
