apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - machine-configs 
  - priorityclass-cluster-role.yaml
  - cluster-role-binding.yaml
  - high_priority.yaml 
  - normal_priority.yaml
  - low_priority.yaml
  - ConsoleNotification.yaml
