apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority 
  labels:
    app.kubernetes.io/instance: cluster-setting
value: 500000 
preemptionPolicy: PreemptLowerPriority 
globalDefault: false 
description: "This priority class should be used for Low service pods only." 
