---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
  labels:
    app.kubernetes.io/instance: cluster-setting
value: 1000000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for High service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: low-priority
  labels:
    app.kubernetes.io/instance: cluster-setting
value: 500000
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "This priority class should be used for Low service pods only."
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: normal-priority
  labels:
    app.kubernetes.io/instance: cluster-setting
value: 750000
preemptionPolicy: PreemptLowerPriority
globalDefault: true
description: "This priority class should be used for normal service pods only."

