apiVersion: route.openshift.io/v1
kind: Route
namespaces: namespace1
metadata:
  name: test-app
spec:
  host: test-app-my-namespace.apps.ocp4.tingnkai.com
  port:
    targetPort: 8080 
  to:
    kind: Service
    name: test-app 
