apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: test-app
    name: test-app
  name: test-app
spec:
  ports:
  - port: 8080
  selector:
    name: test-app
