apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ldap-sync-service-account.yaml
  - ldap-sync-cluster-role.yaml
  - ldap-sync-cluster-role-binding.yaml
  - ldap-sync-config-map.yaml
  - ldap-sync-cron-job.yaml
