---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync 
  labels:
    app: cronjob-ldap-group-sync
data:
  ldap-group-sync.yaml: |
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldaps://dc01.tingnkai.com
    bindDN: CN=ldapuser,CN=Users,DC=tingnkai,DC=com
    bindPassword:
      file: "/etc/secrets/bindPassword"
    ca: /etc/ldap-ca/ca.crt
    insecure: false
    rfc2307:
        groupsQuery:
          baseDN: "DC=tingnkai,DC=com"
          scope: sub
          derefAliases: never
          filter: (objectclass=group)
        groupUIDAttribute: dn
        groupNameAttributes: [ cn ]
        groupMembershipAttributes: [ member ]
        usersQuery:
            baseDN: "DC=tingnkai,DC=com"
            scope: sub
            derefAliases: never
            pageSize: 0
        userUIDAttribute: dn
        userNameAttributes: [ sAMAccountName ]
        tolerateMemberNotFoundErrors: true
        tolerateMemberOutOfScopeErrors: true
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer-whitelist
  namespace: ldap-sync
  labels:
    app: cronjob-ldap-group-sync
data:
  whitelist.txt: |
    CN=OCP-Admins,CN=Users,DC=tingnkai,DC=com
    CN=Developers,CN=Users,DC=tingnkai,DC=com

