---
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  identityProviders:
    - ldap:
        attributes:
          email:
            - mail
          id:
            - sAMAccountName
          name:
            - cn
          preferredUsername:
            - sAMAccountName
        bindDN: 'CN=ldapuser,CN=Users,DC=tingnkai,DC=com'
        bindPassword:
          name: ldap-bind-password
        ca:
          name: tingnkai-ca
        insecure: false
        url: 'ldaps://dc01.tingnkai.com:636/cn=Users,dc=tingnkai,dc=com?sAMAccountName?sub'
      mappingMethod: claim
      name: ldapidp
      type: LDAP
