apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: quota-limit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: quota-limit-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
